//自定义css属性顺序规则
module.exports = {
    //"extends 默认 ？"
    "extends": [
        "stylelint-config-standard"
    ],
	// https://stylelint.io/user-guide/configure/#overrides
	"overrides": [{
		customSyntax: "postcss-scss",
		files: ["**/*.css", "**/*.scss"]
	}, {
		// 校验HTML和Vue的CSS时开启配置的stylelint.configBasedir和stylelint.customSyntax
		//https://stylelint.io/migration-guide/to-14/
		customSyntax: "postcss-html",··
		files: ["**/*.html", "**/*.vue"]
	}]
    "plugins": ["stylelint-order"],
    "rules": {
		//esling: Require quotes around object literal property names
		//https://eslint.org/docs/latest/rules/quote-props
		/* eslint-disable quote-props */

		//alpha-value-notation: Specify percentage or number notation for alpha-values (Autofixable).
		"alpha-value-notation": "number",
		// at-rule-empty-line-before: Require or disallow an empty line before at-rules (Autofixable).
		"at-rule-empty-line-before": "never",
		//不验证@未知的名字，为了兼容scss的函数
		"at-rule-no-unknown": [true, { ignoreAtRules: ["content", "each", "error", "extend", "for", "function", "if", "include", "mixin", "return", "while"] }],
		// color-function-notation: Specify modern or legacy(传统) notation for applicable color-functions (Autofixable).
		"color-function-notation": "legacy",
		// color-no-invalid-hex: Disallow invalid hex colors.
		"color-no-invalid-hex": true,
		//https://stylelint.io/user-guide/rules/about/#whitespace-rules
		"comment-empty-line-before": "never",
		//custom-property-empty-line-before: Require or disallow an empty line before custom properties (Autofixable).
		"custom-property-empty-line-before": "never",
		//declaration-colon-newline-after: Require a newline or disallow whitespace after the colon of declarations (Autofixable).
		"declaration-colon-newline-after": null,
		// declaration-empty-line-before: Require or disallow an empty line before declarations (Autofixable).
		"declaration-empty-line-before": "never",
		// function-linear-gradient-no-nonstandard-direction: Disallow direction values in linear-gradient() calls that are not valid according to the standard syntax.
		"function-linear-gradient-no-nonstandard-direction": null,
		//function-no-unknown: Disallow unknown functions.
		"function-no-unknown": null,
		//indentation: Specify indentation (Autofixable).
		"indentation": "tab",
		// max-line-length: Limit the length of a line.
		"max-line-length": null,
		//禁止低优先级的选择器出现在高优先级的选择器之后
		"no-descending-specificity": null,
		//no-empty-source: Disallow empty sources.
		"no-empty-source": null,
		// no-missing-end-of-source-newline: Disallow missing end-of-source newlines (Autofixable).
		"no-missing-end-of-source-newline": null,
		//禁止小于1的小数有一个前导零
		"number-leading-zero": "never",
		"order/order": [
			"custom-properties",
			"declarations"
		],

        //先引入 plugins 插件 => stylelint-order， 然后在 order/properties-order 里面写css属性的先后顺序
		//属性的排序
        "order/properties-order": [
            //布局属性
            "display",
            "visibility",
            "overflow",
            "overflow-x",
            "overflow-y",
            "scroll-behavior",
            "scroll-snap-align",
            //布局属性：浮动
            "float",
            "clear",
            //布局属性：定位
            "position",
            "left",
            "right",
            "top",
            "bottom",
            "z-index",
            //布局属性：列表
            "list-style",
            "list-style-type",
            "list-style-position",
            "list-style-image",
            //布局属性：表格
            "table-layout",
            "border-layout",
            "border-spacing",
            "caption-side",
            "empty-cells",
            //布局属性：弹性
            "flex-flow",
            "flex-direction",
            "flex-warp",
            "justify-content",
            "align-items",
            "align-self",
            "flex",
            "flex-grow",
            "flex-shrink",
            "flex-basis",
            "order",
            //布局属性：多列
            "columns",
            "column-width",
            "column-count",
            "column-gap",
            "column-rule",
            "column-rule-width",
            "column-rule-style",
            "column-rule-color",
            "column-span",
            "column-fill",
            "column-break-before",
            "column-break-after",
            "column-break-inside",
            //布局属性：格栅
            "grid-columns",
            "grid-rows",
            //尺寸属性：
            "box-sizing",
            "margin",
            "margin-left",
            "margin-right",
            "margin-top",
            "margin-bottom",
            "padding",
            "padding-left",
            "padding-right",
            "padding-top",
            "padding-bottom",
            "border",
            "border-width",
            "border-style",
            "border-color",
            "border-colors",
            "border-radius",
            "border-top-left-radius",
            "border-top-right-radus",
            "border-bottom-left-radius",
            "border-bottom-right-radius",
            "border-left",
			"border-left-width",
			"border-left-style",
			"border-left-color",
			"border-left-colors",
			"border-right",
			"border-right-width",
			"border-right-style",
			"border-right-color",
			"border-right-colors",
			"border-top",
			"border-top-width",
			"border-top-style",
			"border-top-color",
			"border-top-colors",
			"border-bottom",
			"border-bottom-width",
			"border-bottom-style",
			"border-bottom-color",
			"border-bottom-colors",
            "border-image",
			"border-image-source",
			"border-image-slice",
			"border-image-width",
			"border-image-outset",
			"border-image-repeat",
			"width",
			"min-width",
			"max-width",
			"height",
			"min-height",
			"max-height",
			// 界面属性
			"appearance",
			"outline",
			"outline-width",
			"outline-style",
			"outline-color",
			"outline-offset",
			"outline-radius",
			"outline-radius-topleft",
			"outline-radius-topright",
			"outline-radius-bottomleft",
			"outline-radius-bottomright",
			"background",
			"background-color",
			"background-image",
			"background-repeat",
			"background-repeat-x",
			"background-repeat-y",
			"background-position",
			"background-position-x",
			"background-position-y",
			"background-size",
			"background-origin",
			"background-clip",
			"background-attachment",
			"bakground-composite",
			"mask",
			"mask-mode",
			"mask-image",
			"mask-repeat",
			"mask-repeat-x",
			"mask-repeat-y",
			"mask-position",
			"mask-position-x",
			"mask-position-y",
			"mask-size",
			"mask-origin",
			"mask-clip",
			"mask-attachment",
			"mask-composite",
			"mask-box-image",
			"mask-box-image-source",
			"mask-box-image-width",
			"mask-box-image-outset",
			"mask-box-image-repeat",
			"mask-box-image-slice",
			"box-shadow",
			"box-reflect",
			"backdrop-filter",
			"mix-blend-mode",
			"filter",
			"opacity",
			"object-fit",
			"clip",
			"clip-path",
			"resize",
			"zoom",
			"cursor",
			"pointer-events",
			"touch-callout",
			"user-modify",
			"user-focus",
			"user-input",
			"user-select",
			"user-drag",
			// 文字属性
			"line-height",
			"line-clamp",
			"vertical-align",
			"direction",
			"unicode-bidi",
			"writing-mode",
			"ime-mode",
			"text-overflow",
			"text-decoration",
			"text-decoration-line",
			"text-decoration-style",
			"text-decoration-color",
			"text-decoration-skip",
			"text-underline-position",
			"text-align",
			"text-align-last",
			"text-justify",
			"text-indent",
			"text-stroke",
			"text-stroke-width",
			"text-stroke-color",
			"text-shadow",
			"text-transform",
			"text-size-adjust",
			"src",
			"font",
			"font-family",
			"font-style",
			"font-stretch",
			"font-weight",
			"font-variant",
			"font-size",
			"font-size-adjust",
			"color",
			// 内容属性
			"tab-size",
			"overflow-wrap",
			"word-wrap",
			"word-break",
			"word-spacing",
			"letter-spacing",
			"white-space",
			"caret-color",
			"quotes",
			"content",
			"content-visibility",
			"counter-reset",
			"counter-increment",
			"page",
			"page-break-before",
			"page-break-after",
			"page-break-inside",
			// 交互属性
			"will-change",
			"perspective",
			"perspective-origin",
			"backface-visibility",
			"transform",
			"transform-origin",
			"transform-style",
			"transition",
			"transition-property",
			"transition-duration",
			"transition-timing-function",
			"transition-delay",
			"animation",
			"animation-name",
			"animation-duration",
			"animation-timing-function",
			"animation-delay",
			"animation-iteration-count",
			"animation-direction",
			"animation-play-state",
			"animation-fill-mode",
			// Webkit专有属性
			"-webkit-overflow-scrolling",
			"-webkit-box-orient",
			"-webkit-line-clamp",
			"-webkit-text-fill-color",
			"-webkit-tap-highlight-color"
        ],

		//rule-empty-line-before: Require or disallow an empty line before rules (Autofixable).
		"rule-empty-line-before": "never"
		/* eslint-enable quote-props */
    }
}